export { default as Header } from './Header'
export { default as MainContent } from './MainContent'
export { default as Logo } from './Logo'
export { default as Divider } from './Divider'
export { default as EmptyCard } from './EmptyCard'
export { default as EmptyPhoto } from './EmptyPhoto'
export { default as Camera } from './Camera'